<a href="https://colab.research.google.com/github/galbendavids/deep_learning_projects/blob/main/Nureal_network_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
def initialize_parameters(layer_dims):#need to check with shay
  W = []
  b = []
  for layer in range(1, len(layer_dims)):
    #Return a sample (or samples) from the “standard normal” distribution.
    b.append(np.zeros(layer_dims[layer]))
    #shays code
    W.append(np.random.randn(layer_dims[layer],layer_dims[layer-1]))
    ################
    #NEW TRY, i think we need to transpose the weights
    #W.append((np.random.randn(layer_dims[layer],layer_dims[layer-1])).T)
    ################
  return np.array(W),np.array(b)
print(initialize_parameters([2,3,1])[0])

[array([[-0.3863887 ,  0.03868427],
       [-0.25262791,  0.66689991],
       [-0.08579473,  0.58145371]])
 array([[-0.47192173,  0.5673913 ,  0.11664484]])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  del sys.path[0]


In [ ]:
def linear_forward(A, W, b): 
  Z = W.dot(A) + b
  return Z, {'linear_cache': [A, W, b]} # fix return a dic not array
a = np.array([[ 5, 1 ,3], 
              [ 1, 1 ,1], 
              [ 1, 2 ,1]])
b = np.array([1, 2, 3])
linear_forward(b, a, np.ones(3))

(array([17.,  7.,  9.]), {'linear_cache': [array([1, 2, 3]), array([[5, 1, 3],
          [1, 1, 1],
          [1, 2, 1]]), array([1., 1., 1.])]})

In [ ]:
def softmax(Z):
  return np.exp(Z) / np.sum(np.exp(Z)), {'activation_cache': [Z]}

In [ ]:
import copy
def relu(Z):
  Z_relu = copy.deepcopy(Z) # check if must
  Z_relu[Z<0]=0
  return Z_relu, {'activation_cache': [Z]}

x = np.random.randn(2,2)
print(relu(x))

(array([[0.        , 1.41480948],
       [1.67232025, 0.        ]]), {'activation_cache': [array([[-1.36652612,  1.41480948],
       [ 1.67232025, -0.47674891]])]})


In [ ]:
def linear_activation_forward(A_prev, W, B, activation): #need to check
  Z, linear_cache = linear_forward(A_prev, W, B)
  if activation == "relu":
    output, activation_cache = relu(Z)
    linear_cache.update(activation_cache)
    return output, linear_cache
  else: # softmax
    output, activation_cache = softmax(Z)
    linear_cache.update(activation_cache)
    return output, linear_cache
linear_activation_forward(np.random.randn(5,4), initialize_parameters([5,5])[0], initialize_parameters([5,4])[1], "x")

(array([[[5.69239886e-03, 8.44855094e-02, 2.53759232e-03, 4.09446166e-03],
         [5.92295574e-01, 8.79306681e-02, 6.18184453e-03, 4.14218053e-03],
         [6.30725853e-03, 2.24067524e-02, 2.80270502e-02, 8.63415740e-03],
         [3.11861133e-02, 3.17372366e-02, 1.23087722e-02, 5.59012098e-03],
         [3.76904006e-04, 5.63717808e-02, 6.14315277e-03, 3.55047125e-03]]]),
 {'activation_cache': [array([[[-1.08213288,  1.6153154 , -1.89004891, -1.41162939],
           [ 3.56274116,  1.65528401, -0.99964794, -1.40004229],
           [-0.97956352,  0.28809773,  0.51190549, -0.66553851],
           [ 0.61870827,  0.63622601, -0.31095244, -1.10026371],
           [-3.79702939,  1.21070406, -1.00592654, -1.55418429]]])],
  'linear_cache': [array([[ 0.29544011, -1.25253613,  0.61781314,  1.23621274],
          [-0.92074263, -0.71017019,  0.20463074,  0.54179585],
          [-2.34367611,  0.181712  , -1.02903811, -0.65666005],
          [ 2.06059389,  0.04124191,  0.11360048,  0.08596826],
 

In [ ]:
#1f
def L_model_forward(X, parameters, use_batchnorm): #need to check with shay


  ##for section 3 and 4
  if(use_batchnorm):
    #do something
    print(use_batchnorm)
  ##

  cache={}
  W,B = parameters
  L=parameters[0].shape[0]+1 #num of layers
  
  A=X #installation. is that true?

  for i in range(0,L-2): # in L layer net there are L-2 feeding forwards

    
    #printing for debuging, delete after shays checks it
    print("iteration:"+ str(i))
    print("A")
    print(X)
    print(X.shape)
    print("W")
    print(W[i].T)
    print(W[i].T.shape)
    print("B")
    print(B[i])
    print(B[i].shape)
    #printing for debugging --- > end

    Z, linear_cache = linear_forward( W[i].T,A, B[i].T)
    cache.update(linear_cache)
    A, activation_cache = relu(Z)
    cache.update(activation_cache)
  
  Z, linear_cache = linear_forward(W[L-2].T,A, B[L-2].T)
  cache.update(linear_cache)
  AL, activation_cache = softmax(Z)
  cache.update(activation_cache)
  return AL, cache


input_size=3
num_of_examples=5
X=np.random.randn(num_of_examples,input_size)
parameters=initialize_parameters([input_size,3,3,3,1])
use_batchnorm=False #should we apple bactchnorm after activatin - 
                    #note that this option needs to be set to “false” in Section 3 and “true” in Section 4

AL_,cache_=(L_model_forward(X,parameters,False))


iteration:0
A
[[ 1.19665584  0.76827184 -0.07305142]
 [-0.79789926 -0.79493072  0.13863908]
 [ 0.80394854  0.09121762  0.24100775]
 [-1.37567168 -0.15665453  0.12848972]
 [-0.53707113 -0.03480119  0.08074453]]
(5, 3)
W
[[ 1.88617078  0.58190462  0.01052073]
 [-1.2032277   1.49277819  0.7156293 ]
 [-3.04612755  0.79899008  0.36959002]]
(3, 3)
B
[0. 0. 0.]
(3,)
iteration:1
A
[[ 1.19665584  0.76827184 -0.07305142]
 [-0.79789926 -0.79493072  0.13863908]
 [ 0.80394854  0.09121762  0.24100775]
 [-1.37567168 -0.15665453  0.12848972]
 [-0.53707113 -0.03480119  0.08074453]]
(5, 3)
W
[[-0.47631961  0.57867524 -0.03363722]
 [ 1.16347718 -1.71294858 -0.0253761 ]
 [-0.20437755 -0.32438223  0.01625974]]
(3, 3)
B
[0. 0. 0.]
(3,)
iteration:2
A
[[ 1.19665584  0.76827184 -0.07305142]
 [-0.79789926 -0.79493072  0.13863908]
 [ 0.80394854  0.09121762  0.24100775]
 [-1.37567168 -0.15665453  0.12848972]
 [-0.53707113 -0.03480119  0.08074453]]
(5, 3)
W
[[-1.13603346  0.73428284  0.82489614]
 [-1.1271307  -1.9

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  del sys.path[0]


In [ ]:
#1g


def compute_cost(AL, Y):  #need to check with shay
  m=AL.shape[1]
  cost_matrix = (np.dot(Y, np.log(AL).T) + np.dot(1 - Y, np.log(1-AL).T))
  cost_value=(-1/m)*sum(sum(cost_matrix))
  return cost_value

#trial
compute_cost(AL_,AL_*2)# not real values.. only for the example..

20.966153274936996

In [ ]:
#2 
def	linear_backward(dZ, cache):
  A_prev, W, b_prev = cache['linear_cache']
  dW = dZ.dot(A_prev.T) # sould do Transpse?
  db = dZ.dot(np.ones(np.shape(dZ)[1]))
  dA_prev = W.T.dot(dZ)
  return dA_prev, dW, db

#a = np.array([[ 1 ,3], 
#              [ 1 ,1], 
#              [ 2 ,1]])
#b = np.array([[1], [2]])
linear_backward(np.random.randn(3,1), linear_forward(b, a, np.ones(3))[1])

In [ ]:
def	relu_backward(dA, activation_cache):
  Z = activation_cache["activation_cache"][0] # need to check
  dZ = copy.deepcopy(dA)
  dZ[Z<0] = 0 
  return dZ

In [ ]:
def softmax_backward(dA, activation_cache):
  Z = activation_cache["activation_cache"][0]
  sig = 1 / (1 + math.exp(-x))
  dZ = dA * sig(Z) * (1 - sig(Z))
  return dZ

In [ ]:
def linear_activation_backward(dA, cache, activation):
  if activiation == "relu":
    dZ = relu_backward(dA, cache)
  else:
    dZ = softmax_backward(dA, cache)
  dA_prev, dW, db = linear_backward(dZ, cache)
  return dA_prev, dW, db

In [ ]:
def L_model_backward(AL, Y, caches):
  #dA_priv sould be clac
  dA_prob = None
  Grads = {}
  counter = len(caches)
  for cache in caches[::-1]:
    dA_prev, dW, db = linear_activation_backward(dA_prob, cache, "relu")
    Grands["dA"+str(counter)] = dA_prev
    Grands["dW"+str(counter)] = dW
    Grands["db"+str(counter)] = db
    dA_prob = copy.deepcopy(dA_prev)

In [ ]:
def Update_parameters(parameters, grads, learning_rate):
  
  return parameters 

In [ ]:
def L_layer_model(X, Y, layers_dims, learning_rate, num_iterations, batch_size):
  pass

In [ ]:
while True:
  pass